sudo: false
language: cpp
compiler:
  - g++
os:
  - linux
branches:
    # expected format: v1.0.0
  only:
    - /^v\d+(\.\d+)+$/
before_deploy:
  - cd ..
  - tar -zcf ${TRAVIS_BUILD_DIR}${REPO}-${BUILD_ENV}-${TRAVIS_TAG}-${TRAVIS_BUILD_NUMBER}.tar.gz ${REPO}
  
deploy:
    # GitHub - Add zip to release
  - provider: releases
    api_key:
      secure: "7d45e49b791aa94146470c469b392118427dd65f"
      file: ${TRAVIS_BUILD_DIR}${REPO}-${BUILD_ENV}-${TRAVIS_TAG}-${TRAVIS_BUILD_NUMBER}.tar.gz
      skip_cleanup: true
    on:
      tags: true